services:
 
   # MySQL Database (Shared between all services)
   # mysql -h 127.0.0.1 -P 3307 -u root -p
   # create database shared_db
  shared-db:
    image: mysql:8.0
    container_name: shared-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microDb
    volumes:
      - shared-db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  # Eureka service registry
  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server-service
    ports:
      - "8761:8761"

  # Spring cloud api-gateway service
  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway-service
    env_file: ".env"
    ports:
      - "8079:8079"
    depends_on:
      - eureka-server

  # Authentication service
  authentication-service:
    image: authentication:latest
    container_name: authentication-service
    ports:
      - "8081:8081"
    env_file: ".env"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://shared-db:3306/shared_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - eureka-server
      - api-gateway

  # Product service
  product-service:
    image: product-service:latest
    container_name: product-service
    ports:
      - "8083:8083"
    env_file: ".env"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://shared-db:3306/shared_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - eureka-server
      - api-gateway

  # Customer service
  customer-service:
    image: customer-service:latest
    container_name: customer-service
    ports:
      - "8084:8084"
    env_file: ".env"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://shared-db:3306/shared_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - eureka-server
      - api-gateway

  # Client app
  app:
    image: app:latest
    container_name: zip-app-service
    env_file: ".env"
    ports:
      - "9091:9091"
    depends_on:
      - eureka-server
      - api-gateway
 # admin-client
  admin-client:
    image: admin-client:latest
    container_name: zip-admin-client
    env_file: ".env"
    ports:
      - "8089:8089"
    depends_on:
      - eureka-server
      - api-gateway

  # Customer service
  review-service:
    image: review-service:latest
    container_name: review-service
    ports:
      - "8077:8077"
    env_file: ".env"
    depends_on:
      - eureka-server
      - api-gateway

  # Prometheus monitoring service
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - product-service

  # Grafana dashboard service
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana-dashboard
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  shared-db-data:
  grafana-storage: {}
