spring:
  application:
    name: app
  # JSP setup
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: logs/app.log      
  level:
    root: info                
